%% Result path
pdata = '+tvt_activity/data/s_Inf/';

close all;
tvt_activity.helpers.getFigLOS( {  strcat(pdata, 'assoc_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'assoc_Validation_30_180_2_A.mat') }, ...
    'Fig_2');
close all;
tvt_activity.helpers.getFigH(strcat(pdata, 'pL_30_180_1_A.mat'), [2.4 3.1], [0 900], false, 'Fig_Ea');
close all;
tvt_activity.helpers.getFigH(strcat(pdata, 'pL_30_180_1_A.mat'), [0.1 0.5], [0 11000], true, 'Fig_Eb');
close all;
tvt_activity.helpers.getFigH(strcat(pdata, 'pL_30_180_2_A.mat'), [2 11], [0 1100], false, 'Fig_Fa');
close all;
tvt_activity.helpers.getFigH(strcat(pdata, 'pL_30_180_2_A.mat'), [0.1 0.7], [0 11000], true, 'Fig_Fb');
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    50, ...
    'Fig_3a');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    50, ...
    'Fig_3a_zoom', 0.16);
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    20, ...
    'Fig_3b');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    20, ...
    'Fig_3b_zoom', 0.16);
close all
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    50, ...
    'Fig_4a');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    50, ...
    'Fig_4a_zoom', 0.16);
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    20, ...
    'Fig_4b');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    20, ...
    'Fig_4b_zoom', 0.16);
close all
tvt_activity.helpers.getFigLamb( {  strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat') }, ...
    [6, 11], ...
    'Fig_5', true);
close all;
close all
tvt_activity.helpers.getFigLambZoom( {  strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat') }, ...
    [6, 11], ...
    'Fig_5_zoom', true);
close all;
tvt_activity.helpers.getFigRate( {  strcat(pdata, 'rate_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'rate_Validation_30_180_2_A.mat')}, ...
    {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat')}, ...
    'Fig_6');
close all;
