%% Result path
pdata = '+tvt_activity/data/s_Inf/';

close all;
tvt_activity.helpers.getFigLOS( {  strcat(pdata, 'assoc_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'assoc_Validation_30_180_2_A.mat') }, ...
    'Fig_3');
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    50, ...
    'Fig_4a');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    50, ...
    'Fig_4a_zoom');
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    20, ...
    'Fig_4b');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_1_A.mat') }, ...
    20, ...
    'Fig_4b_zoom');
close all
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    50, ...
    'Fig_5a');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    50, ...
    'Fig_5a_zoom');
close all;
tvt_activity.helpers.getFig( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    20, ...
    'Fig_5b');
close all;
tvt_activity.helpers.getFigZoom( {  strcat(pdata, 'data_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_B.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat'), ...
    strcat(pdata, 'data_Validation_90_180_2_A.mat') }, ...
    20, ...
    'Fig_5b_zoom');
close all
tvt_activity.helpers.getFigLamb( {  strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat') }, ...
    [11, 16], ...
    'Fig_6', true);
close all;
tvt_activity.helpers.getFigRate( {  strcat(pdata, 'rate_Validation_30_180_2_B.mat'), ...
    strcat(pdata, 'rate_Validation_30_180_2_A.mat')}, ...
    'Fig_7');
close all;
