%% Result path
pdata = '+tvt_activity/data/s_0_off/';

close all;
tvt_activity.helpers.getFigLamb( {  strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat') }, ...
    [6, 11], ...
    'Fig_7', true);
close all;
tvt_activity.helpers.getFigLambZoom( {  strcat(pdata, 'data_Validation_30_180_1_A.mat'), ...
    strcat(pdata, 'data_Validation_30_180_2_A.mat') }, ...
    [6, 11], ...
    'Fig_7_zoom', true);
close all;
